export {
  useBlockerTable as useRiskTable,
  BLOCKER_SEVERITY_DOT as RISK_SEVERITY_DOT,
  BLOCKER_SEVERITY_TEXT as RISK_SEVERITY_TEXT,
  BLOCKER_STATUS_TEXT as RISK_STATUS_TEXT,
  BLOCKER_SEVERITY_STYLE as RISK_SEVERITY_STYLE,
  BLOCKER_STATUS_STYLE as RISK_STATUS_STYLE,
} from '@/composables/useBlockerTable';
