/** Gợi ý tooltip / placeholder cho form phiếu đề xuất AI (PDX). */
export const PROPOSAL_FORM_HINTS = {
    proposal_type: 'Phân loại phiếu: AI Account, SaaS, License, … — ảnh hưởng mẫu in và báo cáo.',
    subject_about: 'Dòng «Về việc» trên phiếu PDX. Thường bắt đầu bằng «Đăng ký sử dụng …».',
    send_to: 'Mỗi dòng một đơn vị nhận phiếu. Dòng 1 thường là Ban Giám đốc; dòng 2 trở đi là các phòng (VD: Phòng Công nghệ & Phòng Kế Toán). Nhấn Enter để xuống dòng.',
    proposer_pick: 'Gõ họ tên, email hoặc mã nhân viên vào ô tìm — chọn dòng trong danh sách để tự điền các trường bên dưới. Có thể gõ từng phần (VD: «Toàn» hoặc «bui toan»).',
    proposer_name: 'Họ tên người ký phiếu đề xuất (mục 1 — Đại diện).',
    proposer_position: 'Chức vụ trên phiếu (VD: Chuyên viên, Trưởng nhóm).',
    proposer_department: 'Đơn vị / phòng ban của người đề xuất.',
    tool_name: 'Tên sản phẩm hoặc công cụ trên bảng ngân sách và nội dung phiếu. Chọn gợi ý để tự điền gói & chi phí nếu đã có trong hệ thống.',
    vendor_name: 'Tên nhà cung cấp / hãng (OpenAI, Anthropic, Microsoft, …).',
    vendor_website: 'Trang chủ hoặc trang đặt hàng để tham chiếu khi duyệt.',
    proposal_content: 'Tóm tắt nội dung mục 2 trên phiếu. Tối thiểu 20 ký tự, nên nêu rõ phạm vi và thời gian sử dụng.',
    description: 'Chi tiết kỹ thuật, phiên bản, tích hợp — không bắt buộc nhưng hữu ích khi duyệt.',
    reason_for_proposal: 'Lý do cần mua / gia hạn: vấn đề hiện tại và hậu quả nếu không có.',
    objectives: 'Mục tiêu mục 3 — mỗi dòng một ý (bullet trên phiếu in).',
    expected_benefit: 'Kỳ vọng định lượng hoặc định tính sau khi triển khai.',
    group_function: 'Nhóm chức năng (DEV, BA, Design, …) để gom chi phí trong báo cáo.',
    license_type: 'Tên gói từ nhà cung cấp (Pro, Team, Business, …). Gõ hoặc chọn gợi ý.',
    cost_amount: 'Số tiền một chu kỳ thanh toán (VNĐ, số nguyên). Hệ thống quy đổi ra VNĐ/tháng trên phiếu.',
    cost_unit: 'Chu kỳ áp dụng cho số tiền nhập ở trên (tháng, quý, năm, một lần).',
    quantity: 'Số dòng / số lượng trên bảng ngân sách mục 4.1 (thường là 1).',
    purchase_type: 'Mua mới hoặc gia hạn license đang dùng — hiển thị mục 4.4 trên phiếu.',
    planned_use_date: 'Ngày dự kiến đưa vào sử dụng (mục 5, in đỏ trên phiếu).',
    registration_email: 'Email đăng ký với nhà cung cấp (mục 4.5 nếu có).',
    seats: 'Số tài khoản / seat trên gói Team hoặc Business.',
    staff_count: 'Số nhân sự sử dụng thực tế (mục 4.2). Có thể khác số seat.',
    department_using: 'Bộ phận chính sử dụng công cụ sau khi duyệt.',
    users_list: 'Danh sách tên từng người dùng — mỗi dòng một tên, khớp nhân sự thực tế.',
    start_date: 'Ngày bắt đầu chu kỳ license hoặc triển khai (nội bộ).',
    end_date: 'Ngày kết thúc dự kiến (nội bộ, nhắc gia hạn).',
    copy_recipient: 'Tự điền người tiếp nhận license giống người đề xuất.',
    recipient_name: 'Người phối hợp nhận tài khoản sau khi duyệt (mục 4.3).',
    recipient_email: 'Email liên hệ khi IT / Kế toán bàn giao tài khoản.',
    recipient_phone: 'Số điện thoại liên hệ tiếp nhận.',
};
